### PR TITLE
#56: Run locally "cikit selenium" during VM provisioning

### PR DESCRIPTION
**Pull request by BR0kEN-**

### CODE REVIEW

**Comment by lokeoke** [comment]
Please provide more info, why do we need ` && true` here?

**Comment by BR0kEN-** [comment]
@lokeoke is this not enough - https://github.com/BR0kEN-/cikit/issues/56#issue-270286138?

**Comment by BR0kEN-** [comment]
@lokeoke the reason is that `cikit` provisioner runs a Bash command (https://github.com/BR0kEN-/cikit/blob/master/vagrant/provisioners/cikit/provisioner.rb#L7) and without `&& true` it'll look like `/usr/local/share/cikit/vagrant/../bash/cikit /usr/local/share/cikit/vagrant/../scripts/selenium --limit=default` that makes impossible the playbook from being run because of `--limit=default` - which is a name of VM (it is available on `localhost` only, so no `--limit=WHATEVER` must have not been specified).

Adding the `&& true` the command will start looking like `/usr/local/share/cikit/vagrant/../bash/cikit /usr/local/share/cikit/vagrant/../scripts/selenium && true --limit=default`. `true` command will take all the "uncomfortable" options and allow to execute the `selenium` playbook without them - as I want it to be.

**Comment by BR0kEN-** [comment]
Moreover, I've decided to use `&&` instead of `||` to have the right-hand side of expression executed all the time to avoid hidden surprises if the `cikit selenium` somehow will return an exit code that differs from `0`.

**Pull request merged**
